micronaut:
  application:
    name: api
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
redis.uri: redis://localhost
netty:
  default:
    allocator:
      max-order: 3
